-- =============================================================================
-- AC Energy Meter — FRESH SETUP (single-file, full schema)
-- =============================================================================
-- Run this ONCE on an empty database to stand up the whole meter backend from
-- scratch. It is the consolidated final schema: schema.sql + every migration
-- (001–009) already folded in, plus a minimal `locations` table so the backend
-- runs standalone (the meter normally shares the WorkPulse database, which owns
-- `locations`).
--
-- How to run:
--   phpMyAdmin -> pick the DB -> SQL tab -> paste this file -> Go
--   or:  mysql -u <user> -p <database> < fresh_setup.sql
--
-- Idempotent: every table is CREATE TABLE IF NOT EXISTS, so it is safe to run
-- on a database that already has the WorkPulse `locations` table (that table is
-- left untouched) and safe to re-run.
--
-- Engine InnoDB throughout (needed for foreign keys + transactions).
-- Charset utf8mb4.
--
-- After running, create the first admin user by visiting
--   https://<your-domain>/bootstrap.php
-- in a browser (it runs only while ed_users has no admin). Do NOT seed the
-- admin here — bcrypt hashes must be generated by PHP's password_hash().
-- =============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ---------------- locations ----------------
-- Store/site directory. Owned by the WorkPulse app when the meter shares that
-- database; created here (IF NOT EXISTS) only so a standalone meter install has
-- the foreign-key target and the `location_name` the app/dashboard display.
-- If the real WorkPulse `locations` table already exists, this is a no-op and
-- that table is used as-is. Columns mirror the WorkPulse definition.
CREATE TABLE IF NOT EXISTS locations (
  location_id   INT           NOT NULL AUTO_INCREMENT PRIMARY KEY,
  location_name VARCHAR(100)  NOT NULL,
  contact_email VARCHAR(100)  DEFAULT NULL,
  contact_phone VARCHAR(15)   DEFAULT NULL,
  is_active     TINYINT(4)    DEFAULT 1,
  created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  location_code VARCHAR(20)   DEFAULT NULL,
  address       TEXT          DEFAULT NULL,
  latitude      DECIMAL(10,7) DEFAULT NULL,
  longitude     DECIMAL(10,7) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------- ed_users ----------------
-- Meter-app admin/dashboard login. Separate from WorkPulse's own identity.
CREATE TABLE IF NOT EXISTS ed_users (
  id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username        VARCHAR(32)  NOT NULL UNIQUE,
  password_hash   VARCHAR(255) NOT NULL,
  email           VARCHAR(128) NULL,
  is_admin        TINYINT(1)   NOT NULL DEFAULT 0,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login_at   TIMESTAMP    NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------- ed_energy_devices ----------------
-- Auto-registered the first time an ingest POST arrives. `location` binds the
-- meter to a store (locations.location_id); owner_user_id is set by an admin
-- via the meter admin panel.
CREATE TABLE IF NOT EXISTS ed_energy_devices (
  device_id       VARCHAR(32)  PRIMARY KEY,
  friendly_name   VARCHAR(64)  NOT NULL,
  location        INT          NULL,          -- FK -> locations.location_id
  installed_at    DATE         NULL,
  -- Old meter's last reading (kWh) at install. Added to the dashboard Today &
  -- Period totals so figures continue from the meter this device replaced.
  -- (Legacy column name; it no longer represents a kW capacity.)
  capacity_kw     DECIMAL(12,2) NULL,
  notes           TEXT         NULL,
  owner_user_id   INT UNSIGNED NULL,
  -- App-side BLE access PIN. Auto-generated at registration; the firmware never
  -- sees it. The Android app caches authorised PINs at login and gates BLE
  -- access locally.
  ble_pin         VARCHAR(12)  NULL,
  first_seen_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_owner    (owner_user_id),
  KEY idx_location (location),
  CONSTRAINT fk_ed_dev_owner    FOREIGN KEY (owner_user_id) REFERENCES ed_users(id)               ON DELETE SET NULL,
  CONSTRAINT fk_ed_dev_location FOREIGN KEY (location)      REFERENCES locations(location_id)     ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------- ed_device_meta ----------------
-- Per-device latest status, updated on every ingest POST.
CREATE TABLE IF NOT EXISTS ed_device_meta (
  device_id        VARCHAR(32)  PRIMARY KEY,
  fw_version       VARCHAR(16)  NULL,
  last_sync_at     TIMESTAMP    NULL,
  last_seq         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  last_boot_id     INT UNSIGNED  NOT NULL DEFAULT 0,
  total_readings   BIGINT UNSIGNED NOT NULL DEFAULT 0,
  log_interval_sec INT UNSIGNED  NOT NULL DEFAULT 900,
  -- Last relay state the device reported on an ingest POST (live indicator).
  relay_on          TINYINT(1)  NULL,
  relay_mode        VARCHAR(8)  NULL,   -- 'auto' | 'on' | 'off'
  relay_reported_at TIMESTAMP   NULL,
  -- Latest DS1307 drift (signed sec, + = RTC fast) and when it was measured.
  rtc_drift_sec     INT         NULL,
  rtc_drift_at      DATETIME    NULL,
  -- Latest connected-AP Wi-Fi signal strength reported on ingest (dBm, signed).
  wifi_rssi         SMALLINT    NULL,
  -- Latest CR2032 RTC-backup coin-cell voltage reported on ingest (millivolts).
  coincell_mv       SMALLINT UNSIGNED NULL,
  FOREIGN KEY (device_id) REFERENCES ed_energy_devices(device_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------- ed_rtc_drift_log ----------------
-- One row per hourly NTP sync: how far the DS1307 had drifted from true time.
CREATE TABLE IF NOT EXISTS ed_rtc_drift_log (
  id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  device_id   VARCHAR(32) NOT NULL,
  measured_at DATETIME    NOT NULL,   -- NTP time at the sync
  drift_sec   INT         NOT NULL,   -- signed; + = RTC ahead of true time
  rssi_dbm    SMALLINT    NULL,       -- connected-AP Wi-Fi RSSI at this sample
  coincell_mv SMALLINT UNSIGNED NULL, -- CR2032 RTC-backup coin-cell mV at this sample
  received_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_dev_measured (device_id, measured_at),
  KEY idx_dev_time (device_id, measured_at),
  FOREIGN KEY (device_id) REFERENCES ed_energy_devices(device_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------- ed_energy_readings ----------------
-- (device_id, seq) UNIQUE makes duplicate POSTs (firmware retry) a no-op.
CREATE TABLE IF NOT EXISTS ed_energy_readings (
  id              BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  device_id       VARCHAR(32)   NOT NULL,
  seq             BIGINT UNSIGNED NOT NULL,
  wall_time       DATETIME       NOT NULL,
  time_confidence ENUM('exact','approx') NOT NULL DEFAULT 'exact',
  boot_id         INT UNSIGNED   NOT NULL,
  sec_since_boot  INT UNSIGNED   NOT NULL,
  voltage         DECIMAL(6,2)   NOT NULL,
  current_a       DECIMAL(8,3)   NOT NULL,
  power_w         DECIMAL(10,2)  NOT NULL,
  energy_wh       DECIMAL(14,2)  NOT NULL,
  power_factor    DECIMAL(4,3)   NOT NULL,
  frequency_hz    DECIMAL(5,2)   NULL,
  ingested_at     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_device_seq    (device_id, seq),
  KEY idx_device_time          (device_id, wall_time),
  KEY idx_device_date_energy   (device_id, wall_time, energy_wh),
  FOREIGN KEY (device_id) REFERENCES ed_energy_devices(device_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------- ed_ingest_log ----------------
-- Lightweight audit of every POST attempt. Trim manually if it grows.
CREATE TABLE IF NOT EXISTS ed_ingest_log (
  id              BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  device_id       VARCHAR(32)  NULL,
  received_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  rows_in_payload INT          NULL,
  rows_inserted   INT          NULL,
  status          VARCHAR(32)  NOT NULL,
  client_ip       VARCHAR(45)  NULL,
  notes           TEXT         NULL,
  KEY idx_device_time (device_id, received_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------- ed_device_relay_schedule ----------------
-- Per-device relay config for the off-hours AC cutoff. The firmware fetches
-- this in every ingest.php response and drives the relay accordingly.
CREATE TABLE IF NOT EXISTS ed_device_relay_schedule (
  device_id     VARCHAR(32)     NOT NULL PRIMARY KEY,
  -- AC-ALLOWED open hours as a JSON array of windows:
  --   [{days:[0..6], on:"HH:MM", off:"HH:MM"}, ...]
  -- days: 0=Sun, 1=Mon, ..., 6=Sat. The AC is powered inside these windows;
  -- the relay energizes to CUT the AC outside them. Empty array = AC always
  -- allowed (relay never cuts).
  schedule_json TEXT            NOT NULL DEFAULT ('[]'),
  -- Compressor "is-running" watt threshold. Below it the compressor is off, so
  -- cutting is safe; the firmware waits for wattage to drop below this before
  -- opening the relay (never hard-cuts a running compressor).
  compressor_watts INT UNSIGNED NOT NULL DEFAULT 800,
  -- Minutes after off-hours begin to wait for the compressor to cycle off
  -- before cutting anyway (hard-cut deadline).
  grace_min     INT UNSIGNED    NOT NULL DEFAULT 60,
  -- Monotonic version. Bumped on every update. Firmware uses it to detect
  -- whether the config has changed since the last poll.
  version       INT UNSIGNED    NOT NULL DEFAULT 1,
  updated_at    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
                                ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (device_id) REFERENCES ed_energy_devices(device_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;

-- =============================================================================
-- Done. Next: create the first admin at /bootstrap.php, then point the
-- firmware's ingest host at this backend (BLE "Configure backend host" or
-- INGEST_HOST_DEFAULT in config.h).
-- =============================================================================
